### ISSUE TITLE
How is it better than sequoia?

### ISSUE THREAD

**Issue by KOLANICH** [rpgp/rpgp#114]

**Comment by r10s** [comment]
that depends highy on the projected usecase.

- rpgp has a more libre license that allows usage also on eg. ios - eg. sequoia was finally no option for [Delta Chat](https://delta.chat/en/) because of the license, although bindings were already there

- rpgp is a library with a well-defined, relatively small feature-set, where sequoia also tries to be a replacement for the gpg command line tool - that can be good (more options) or bad (sequoia is larger and has a larger attack vector by using more code and dependencies)

there are probably more differences, in general, however, i think it is very nice to have more options for pgp - 3y ago, there was basically nothing when it comes to libraries that can be used cross-platform :)

**Comment by KOLANICH** [comment]
Thanks for the info! Could it be added into the docs?

>there was basically nothing when it comes to libraries that can be used cross-platform

Isn't Java flavour of BouncyCastle crossplatform? Yes, I know, it depends on Java, but it is better than nothing + is written in a memory-safe language.

**Comment by r10s** [comment]
> Isn't Java flavour of BouncyCastle crossplatform?

in practice, if you want to have a native desktop or a ios app, embedding/adding Java-support to your app just to use a library sounds painful.

however, for sure, there are lots of situations where BouncyCastle is perfectly fine - eg. if you are already working in a Java environment.

**Comment by dignifiedquire** [comment]
Another important difference is that all crypto used in rpgp is implemented in pure Rust, whereas sequoia uses nettle, which is implemented in C.
