### ISSUE TITLE
Set up PGP encryption in a mail tool

### ISSUE THREAD

**Issue by soywod** [rpgp/rpgp#161]
Hi maintainer(s),
First of all, thanks a lot for this great lib. The work you did is quite impressive!

I have a project call [himalaya](https://github.com/soywod/himalaya) which is basically a command-line interface for email management (written in Rust). I try to set up end-to-end encryption (ref issue https://github.com/soywod/himalaya/issues/54), but I don't know well about the domain. I started to dig the [RFC](https://datatracker.ietf.org/doc/html/rfc3156) (which helped me a lot), I was able to encrypt and decrypt emails using `gpg` commands.
But then I found your lib. I thought it could be nicer to encrypt/decrypt inside himalaya rather than depending on an external tool such as `gpg`. So I started to use it and I was able to encrypt an email with the public key of the recipient. But then I asked myself "wait, how am I suppose to get the public key of any recipient?". Indeed, by using `gpg` commands I was implicitly using their key manager to get the public key associated to the recipient's email address. **It is not possible to manager public keys with your lib, right?** Is it doable to built my own key manager, or it is better to use an external tool for this purpose (for eg, keeping `gpg` commands just for this)?
The rest of my questions are how to implement properly what I did with `gpg` commands but with `rPGP`. I should admit that it is hard to find documentation. I checked your tests and other issues but it is still a bit confusing for me. I will share in another comment what I have so far for the encryption, then for decryption. I would love to have some feedback!

**Comment by soywod** [comment]
I also have a question about autocrypt, do you have examples on how to use it?

**Comment by link2xt** [comment]
This library is mostly used by Delta Chat, specifically https://github.com/deltachat/deltachat-core-rust/
Delta Chat core does all the management of the keys in SQLite (and recently SQLCipher), parsing of Autocrypt headers etc. rPGP library has no support for this, it only does the encryption and parsing of OpenPGP packets.

Related source code is here:
https://github.com/deltachat/deltachat-core-rust/blob/master/src/peerstate.rs
https://github.com/deltachat/deltachat-core-rust/blob/master/src/pgp.rs
https://github.com/deltachat/deltachat-core-rust/blob/master/src/aheader.rs
https://github.com/deltachat/deltachat-core-rust/blob/master/src/e2ee.rs

rPGP only implements low-level OpenPGP procedures and does not deal with key management. If you don't want to roll your own key management, maybe you want to look at `sequoia` crate: https://gitlab.com/sequoia-pgp/sequoia/-/tree/main/
Their `openpgp` crate roughly corresponding to what rPGP does and `sequoia` is a high-level API to deal with Autocrypt, key management etc., though I don't know how usable it is in the current state.

Since you are building a command line tool, maybe follow unix-way and build on top of command line tools implementing "Stateless OpenPGP CLI" (https://datatracker.ietf.org/doc/draft-dkg-openpgp-stateless-cli/): https://sequoia-pgp.org/projects/
There is a related issue #110 about implementing this for rPGP, although nobody is working on it.

**Comment by soywod** [comment]
> Delta Chat core does all the management of the keys in SQLite (and recently SQLCipher), parsing of Autocrypt headers etc. rPGP library has no support for this, it only does the encryption and parsing of OpenPGP packets.

Fair enough, now I know well the scope of rPGP.

> If you don't want to roll your own key management, maybe you want to look at `sequoia` crate

I already checked `sequoia`, but it looks messy and heavy. Plus their license is too restrictive for himalaya. I don't feel this is a good choice.

> Since you are building a command line tool, maybe follow unix-way and build on top of command line tools implementing "Stateless OpenPGP CLI" (https://datatracker.ietf.org/doc/draft-dkg-openpgp-stateless-cli/)

But this sounds sooo great, it would fit perfectly my use case!

> There is a related issue #110 about implementing this for rPGP, although nobody is working on it.

If I understand well:

- There is a (draft) standard called "Stateless OpenPGP Command Line Interface" [here](https://datatracker.ietf.org/doc/draft-dkg-openpgp-stateless-cli/)
- There is a Rust Trait defining this standard [here](https://docs.rs/sop/latest/sop/)
- There is an open issue on rPGP to implement this trait [here](https://github.com/rpgp/rpgp/issues/110)

So in theory, I could implement it for rPGP (without the CLI, just the trait implem) and then use it inside himalaya (I could even plug the implem to a subcommand, sth like `himalaya pgp encrypt/decrypt/verify/sign…`)

What do you think?

**Comment by soywod** [comment]
> You still need to implement your preferred way of managing keys

Yeah, this is still a problem for me. I think I will stick with `gpg` at least for this part. Or maybe implementing a kind of hook that takes in parameter an email address and returns a public key (if exists).

> Yes, looks like you can implement trait from the `sop`

Maybe I can start implementing functions I need for my use case and then propose a PR. I come back to you if I have questions about the implementation.
