### ISSUE TITLE
Allows creating non utf-8 `String` without `unsafe`

### ISSUE THREAD

**Issue by jRimbault** [rpgp/rpgp#195]
https://github.com/rpgp/rpgp/blob/66c4f76ee7420c51d4f04e1f44400d4ec2d34ffb/src/util.rs#L189-L191

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5b55d6ec60d2b01cf276a700f9ae4a27)

This should probably use one of the [`from_utf8`](https://doc.rust-lang.org/stable/std/str/fn.from_utf8.html) family of [functions](https://doc.rust-lang.org/stable/std/?search=from_utf8) ?

```rust
pub fn read_string(raw: &[u8]) -> String {
    // this would (violently) prevent invalid utf8 to propagate to other parts of the code
    std::str::from_utf8(raw).unwrap().to_owned()
}
```

or

```rust
pub fn read_string(raw: &[u8]) -> String {
    // Marks this place as unsafe but behave the same as the original cast
    unsafe {
        std::str::from_utf8_unchecked(raw).to_owned()
    }
}
```

**Comment by dignifiedquire** [comment]
This needs fixing, but I think there were cases where this wasn't valid utf8, so we definitely need to handle that somehow..

**Comment by VincentWo** [comment]
The problem here isn't that the creation of non utf-8 Strings is possible (since the method doesn't call unsafe methods itself it would be a serious bug in the standard library), it just doesn't interpret utf-8 in any sensible way but splits the inputs in bytes, converting each one to the UTF-8 code unit corresponding to the byte value. This doesn't create invalid utf-8, but nonsensical output in the case of non ASCII Input

For Example:
🦀 U+1F980: CRAB is in utf-8: f0 9f a6 80 and would be turned by this function into:
```
ð 00F0 LATIN SMALL LETTER ETH
 009f [control] (Application Program Control, one of the ASCII Control Characters nobody uses)
¦ 00a6 BROKEN BAR
 0080 [control]
```

This makes the matter better in some regards (no invalid utf-8 strings are created so this isn't undefined behaviour), but worse in others (it is practically impossible to use this functions with Non-ASCII Characters)

If there is interest in fixing this I would love to contribute

**Comment by dignifiedquire** [comment]
@VincentWo yes please, would appreciate a fix for this

**Comment by VincentWo** [comment]
Yes, I will try. What do you want to happen in case of invalid utf-8 though?

The RFC 2440 (don't know whether that's the newest, just the first one I found) writes that utf-8 MAY be assumed and everything else MAY be ignored

This would allow three courses of action:
- Just replace the invalid utf-8 with "U+FFFD replacement character" using [`from_utf8_lossy`](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy)
- Return an error on everything that isn't utf-8

The former would allow users to still receive non UTF-8 User ids for example (no idea how common this is in the wild)

The later would be a hard block for anything non UTF-8, but has a greater chance of printing only correct characters.

I would recommend `from_utf_lossy`, but wanted maintainer input before deciding. 

(There is also the theoretical method of supporting multiple encodings, but this would be a longer task and could be done after any of the easier approach has been implemented)

**Comment by dignifiedquire** [comment]
So my current goal is to be able to roundtrip as much existing key material as possible, which means ideally we should attempt to store it as valid utf8, but if it isn't treat it as just bytes, so we can output it again. So probabyl we need some type like this

```rust
enum CompatString {
  Utf8(String),
  Other(Vec<u8>),
}
```

to support this.

**Comment by VincentWo** [comment]
How open would you be about adding a dependency? There is the [bstr](https://docs.rs/bstr/latest/bstr/) crate supplying a string that is utf-8 by Convention, but also able to contain any bytes. There is a Display Implementation which converts invalid bytes to � and a Debug Implementation which shows hex codes, maintained by BurntSushi this would be probably much more flexible than anything I would come up with :)

**Comment by dignifiedquire** [comment]
bstr looks quite nice. agreed on disabling the unicode feature for code size benefits

**Comment by VincentWo** [comment]
Yes thank you, I will start working on it :)

**Comment by VincentWo** [comment]
You can see my progress so far, although tests are still missing.

I also stumbled on a question: Currently the User Id of the Signer is a String and [rejects invalid utf-8 ](https://github.com/rpgp/rpgp/blob/8e42501119cea413ec52b3df0383dd4454e5a271/src/packet/signature/de.rs#L225), same for the preferred keyserver. I feel that it would be the best to have consistency here, which would either mean moving them all to bstr OR to move the User id of the Signer to bstr, but move the PolicyURI to only accept valid utf-8 since a URI is always utf-8.

I would prefer the later, but wanted to check back to make sure

**Comment by dignifiedquire** [comment]
the latter sounds good to me
