### ISSUE TITLE
Support for librepgps AEAD

### ISSUE THREAD

**Issue by DoumanAsh** [rpgp/rpgp#375]
Subj?
By default open gpg tool uses AEAD so any encrypted message will fail to parse with:
`Unknown packet typ: 20`

**Comment by hko-s** [comment]
The situation about that GnuPG AEAD format ("packet type 20") is unfortunate.

Some context: The "official", vendor-agnostic OpenPGP standard is developed by an [IETF working group](https://datatracker.ietf.org/wg/openpgp/about/), which consists of all parties who are interested in OpenPGP.
That IETF working group has developed the OpenPGP standard ever since RFC 2440 (from November 1998).

The IETF working group has done focused work on an update to the OpenPGP format in the ["crypto refresh" draft](https://datatracker.ietf.org/doc/draft-ietf-openpgp-crypto-refresh/) starting in 01/2021.
The "crypto refresh" document is a shared project of all actors in the OpenPGP ecosystem (initially GnuPG also participated in this effort). The goal is to define a common, official update to the OpenPGP format. That specification work is currently getting finalized, and will be published as RFC 9580 very soon.

However, GnuPG at some point practically dropped out of the IETF working group, and apparently decided to unilaterally emit formats that are not covered by the OpenPGP specification. This decision started having user-facing effects with [GnuPG version 2.4.0](https://lists.gnupg.org/pipermail/gnupg-announce/2022q4/000477.html), which was released in 12/2022.
The GnuPG project has recently started documenting its new formats in a forked version of the OpenPGP specification under the name "LibrePGP".

So while the IETF working group worked on a new shared standard with the involvement of a broad range of experts, the GnuPG project seemed to decide that it would rather produce "facts on the ground", by emitting its preferred format, instead of continuing to participate in the democratic and vendor-independent IETF process.

The "packet type 20" AEAD format that GnuPG produces is effectively a proprietary format of GnuPG. To make matters worse, that GnuPG-specific AEAD format is not just proprietary to GnuPG, it also seems to be problematic from a security perspective: https://eprint.iacr.org/2024/1110

Personally, I hope that GnuPG will join the rest of the OpenPGP ecosystem in using and supporting the new RFC 9580 format, which has been vetted by the IETF process, and enjoyed much serious thought and vetting from a large group of experts (unlike the LibrePGP draft, which appears to be the work on one individual, working more or less alone)

An additional point about GnuPG's proprietary extensions of the OpenPGP format: Many Linux distributions are shipping patched versions of GnuPG 2.4.x, which avoid enabling these proprietary features by default.
The patches allow users to explicitly opt in to GnuPG's "packet type 20" format, but limit proliferation of this format and the inevitable compatibility problems that come with it.
My interpretation is that there is much concern about GnuPG's direction, in the larger Linux space. It seems extremely noteworthy that many of the big distributions feel that GnuPG's proprietary formats are not a good default for their users.

Coming back to rPGP: rPGP intends to add support for the official new OpenPGP formats in  RFC 9580: https://github.com/rpgp/rpgp/blob/main/docs/FAQ.md, but does not currently have plans to support the proprietary "LibrePGP" formats.

After all of this context, my pragmatic recommendation would be to disable the "feature" flag that signals support for GnuPG's "packet type 20" format.
This stops senders from using that format. In broad strokes:
- you need to update your certificate ("public key") to signal to your correspondents that you don't support that format by disabling the feature flag.
- and then make sure your correspondents obtain a copy of this new version of your public key (e.g. by uploading the new version of your certificate to key servers, and telling your correspondents to update. Or by directly sending the new certificate version to your correspondents and telling them to import it).

Let me know if you need more concrete help with any of that.

**Comment by DoumanAsh** [comment]
Ok, got it, after my own research I found out about AEAD being anyway useless so I will disable it when generating keys

**Comment by hko-s** [comment]
For completeness: ["AEAD"](https://en.wikipedia.org/wiki/Authenticated_encryption) is a family of modern cryptographic primitives that represent the current state of the art for a broad range of uses cases for encryption.

The upcoming OpenPGP standard (RFC 9580) also defines formats that use AEAD mechanisms.

While there is no extremely urgent need for AEAD in OpenPGP data encryption (the encryption format in RFC 4880 has no known weaknesses), it is definitely preferable in the longer run to move from the previous OpenPGP mechanism for protected data encryption ([SEIPDv1](https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-13.html#name-version-1-symmetrically-enc)) to modern standardized AEAD constructions in [SEIPDv2](https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-13.html#name-version-2-symmetrically-enc).

The concern in this issue is *how* AEAD mechanisms are used in PGP. And in particular that GnuPG is unfortunately emitting its own proprietary encryption format based on AEAD.

**Comment by DoumanAsh** [comment]
Yes, I understand functional benefit of added auth in AEAD
But to be fair, to me it feels of more like nice to have, since it doesn't really enhance encryption itself, but only guarantees authenticity

I'm not even sure why GNU's version uses it by default
It is definitely something you want to use when you need it

**Comment by hko-s** [comment]
Both SEIPDv1 (from RFC 4880, in November 2007) and SEIPDv2 (from RFC 9580, and based on AEAD) address the same problem: Defending against [malleability](https://en.wikipedia.org/wiki/Malleability_%28cryptography%29). Which is very useful. Without such defense, active attackers can change ciphertext and cause undetected changes in the decrypted plaintext that the recipient sees. Receiving altered plaintext without warning is obviously bad.

GnuPG's "packet type 20" AEAD format is a third approach to the same problem.

As I hinted above, I'm not excited that GnuPG is pushing its proprietary "packet type 20" AEAD mechanism over the standardized SEIPDv1, by default, including for all users of "version 4" (RFC 4880-based) keys.
To me, this default in GnuPG 2.4.x feels like a user-hostile decision. And it's definitely not happening in the spirit of standardization under the IETF umbrella.

One might even wonder and worry if it is an attempt to achieve user lock-in for GnuPG.

**Comment by wiktor-k** [comment]
> Ok, got it, after my own research I found out about AEAD being anyway useless so I will disable it when generating keys

Just for the record the same solution is recommended by the Arch Wiki: https://wiki.archlinux.org/title/GnuPG#Disable_unsupported_AEAD_mechanism (alongside workarounding other GnuPG-isms such as Restricted subkeys).

**Comment by DoumanAsh** [comment]
@hko-s Yes, I understand your position and I'm personally do not need AEAD anyway. Luckily it is easy to create config file for initializing keys so at least I do not need to remember to disable AEAD

@wiktor-k Yes, thank you, I also look up things at arch wiki first to find out how to do anything in Linux 😄
